// SPDX-FileCopyrightText: 2026 Tommi Tauriainen
// SPDX-License-Identifier: MIT

#pragma once

// Generated by topojson2bin -- do not edit by hand. The capacity
// InputGeometry<MaxPoints, MaxRings>/a Workspace's own MaxRingPoints
// need for this dataset, standalone from the sibling data header
// (also generated).

#include <cstddef>

// pointCount/ringCount for InputGeometry<MaxPoints, MaxRings>
// (input_format.h) capacity; maxRingPointCount (this dataset's
// single largest ring/run) for a Workspace's own MaxRingPoints.
// Anonymous: this header may be #include'd alongside another one
// generated the same way, and two identical named struct types
// would conflict.
static constexpr struct
{
    std::size_t pointCount;
    std::size_t ringCount;
    std::size_t maxRingPointCount;
} kWreniumGeoWorldCoastline110mInfo{4997, 126, 1319};
