// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tommi Tauriainen

#include "writer.h"

#include <cctype>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <stdexcept>

#include "wrenium/geo/input_format.h"

namespace wrenium_geo_convert {

namespace {

void appendUint32LE(std::vector<std::uint8_t> &out, std::uint32_t value)
{
    out.push_back(static_cast<std::uint8_t>(value & 0xFFu));
    out.push_back(static_cast<std::uint8_t>((value >> 8) & 0xFFu));
    out.push_back(static_cast<std::uint8_t>((value >> 16) & 0xFFu));
    out.push_back(static_cast<std::uint8_t>((value >> 24) & 0xFFu));
}

void appendFloatLE(std::vector<std::uint8_t> &out, float value)
{
    std::uint32_t bits = 0;
    static_assert(sizeof(bits) == sizeof(value), "expected 32-bit float");
    std::memcpy(&bits, &value, sizeof(bits));
    appendUint32LE(out, bits);
}

} // namespace

std::vector<std::uint8_t> encodeGeometry(const std::vector<Ring> &rings)
{
    std::vector<std::uint8_t> bytes;

    appendUint32LE(bytes, wrenium::geo::kInputGeometryMagic);
    appendUint32LE(bytes, wrenium::geo::kInputGeometryVersion);
    appendUint32LE(bytes, static_cast<std::uint32_t>(rings.size()));

    for (const Ring &ring : rings) {
        appendUint32LE(bytes, static_cast<std::uint32_t>(ring.size()));
        for (const wrenium::geo::GeoPoint &point : ring) {
            appendFloatLE(bytes, point.latRad);
            appendFloatLE(bytes, point.lonRad);
        }
    }

    return bytes;
}

void writeBinaryFile(const std::string &path, const std::vector<std::uint8_t> &bytes)
{
    std::ofstream file(path, std::ios::binary | std::ios::trunc);
    if (!file) {
        throw std::runtime_error("topojson2bin: failed to open output file: " + path);
    }

    file.write(reinterpret_cast<const char *>(bytes.data()), static_cast<std::streamsize>(bytes.size()));
    if (!file) {
        throw std::runtime_error("topojson2bin: failed to write output file: " + path);
    }
}

void writeDataHeaderFile(const std::string &path, const std::string &arrayName, const std::vector<std::uint8_t> &bytes)
{
    std::ofstream file(path, std::ios::trunc);
    if (!file) {
        throw std::runtime_error("topojson2bin: failed to open data header file: " + path);
    }

    // REUSE-IgnoreStart -- these lines emit literal SPDX tags into the
    // *generated* header, not a tag for this file (writer.cpp) itself.
    file << "// SPDX-FileCopyrightText: 2013-2019 Michael Bostock\n";
    file << "// SPDX-License-Identifier: ISC\n\n";
    // REUSE-IgnoreEnd
    file << "#pragma once\n\n";
    file << "// Generated by topojson2bin -- do not edit by hand.\n";
    file << "// Derived from world-atlas TopoJSON data -- see THIRD_PARTY_NOTICES.md.\n";
    file << "// Byte layout matches wrenium::geo::InputGeometryHeader, see\n";
    file << "// include/wrenium/geo/input_format.h. See the sibling *Info header\n";
    file << "// (also generated) for this dataset's point/ring counts.\n\n";
    file << "#include <cstddef>\n";
    file << "#include <cstdint>\n\n";
    file << "static constexpr std::uint8_t " << arrayName << "[] = {\n";

    constexpr std::size_t kBytesPerLine = 12;
    for (std::size_t i = 0; i < bytes.size(); ++i) {
        if (i % kBytesPerLine == 0) {
            file << "    ";
        }

        file << "0x" << std::hex << std::setfill('0') << std::setw(2)
             << static_cast<unsigned>(bytes[i]);

        const bool isLast = (i + 1 == bytes.size());
        if (!isLast) {
            file << ",";
        }

        if ((i % kBytesPerLine == kBytesPerLine - 1) || isLast) {
            file << "\n";
        } else {
            file << " ";
        }
    }

    file << "};\n\n";
    file << "static constexpr std::size_t " << arrayName << "Size = sizeof(" << arrayName << ");\n";

    if (!file) {
        throw std::runtime_error("topojson2bin: failed to write data header file: " + path);
    }
}

void writeInfoHeaderFile(const std::string &path, const std::string &arrayName, std::size_t pointCount, std::size_t ringCount, std::size_t maxRingPointCount)
{
    std::ofstream file(path, std::ios::trunc);
    if (!file) {
        throw std::runtime_error("topojson2bin: failed to open info header file: " + path);
    }

    // REUSE-IgnoreStart -- these lines emit literal SPDX tags into the
    // *generated* header, not a tag for this file (writer.cpp) itself.
    file << "// SPDX-FileCopyrightText: 2026 Tommi Tauriainen\n";
    file << "// SPDX-License-Identifier: MIT\n\n";
    // REUSE-IgnoreEnd
    file << "#pragma once\n\n";
    file << "// Generated by topojson2bin -- do not edit by hand. The capacity\n";
    file << "// InputGeometry<MaxPoints, MaxRings>/a Workspace's own MaxRingPoints\n";
    file << "// need for this dataset, standalone from the sibling data header\n";
    file << "// (also generated).\n\n";
    file << "#include <cstddef>\n\n";
    file << "// pointCount/ringCount for InputGeometry<MaxPoints, MaxRings>\n";
    file << "// (input_format.h) capacity; maxRingPointCount (this dataset's\n";
    file << "// single largest ring/run) for a Workspace's own MaxRingPoints.\n";
    file << "// Anonymous: this header may be #include'd alongside another one\n";
    file << "// generated the same way, and two identical named struct types\n";
    file << "// would conflict.\n";
    file << "static constexpr struct\n";
    file << "{\n";
    file << "    std::size_t pointCount;\n";
    file << "    std::size_t ringCount;\n";
    file << "    std::size_t maxRingPointCount;\n";
    file << "} " << arrayName << "Info{" << pointCount << ", " << ringCount << ", " << maxRingPointCount << "};\n";

    if (!file) {
        throw std::runtime_error("topojson2bin: failed to write info header file: " + path);
    }
}

} // namespace wrenium_geo_convert
