// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Tommi Tauriainen

#include "writer.h"

#include <cctype>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <stdexcept>

#include "wrenium/geo/input_format.h"

namespace wrenium_geo_convert {

namespace {

void appendUint32LE(std::vector<std::uint8_t> &out, std::uint32_t value)
{
    out.push_back(static_cast<std::uint8_t>(value & 0xFFu));
    out.push_back(static_cast<std::uint8_t>((value >> 8) & 0xFFu));
    out.push_back(static_cast<std::uint8_t>((value >> 16) & 0xFFu));
    out.push_back(static_cast<std::uint8_t>((value >> 24) & 0xFFu));
}

void appendFloatLE(std::vector<std::uint8_t> &out, float value)
{
    std::uint32_t bits = 0;
    static_assert(sizeof(bits) == sizeof(value), "expected 32-bit float");
    std::memcpy(&bits, &value, sizeof(bits));
    appendUint32LE(out, bits);
}

std::string toHeaderGuard(const std::string &arrayName)
{
    std::string guard = "WRENIUM_GEO_CONVERT_GENERATED_";
    for (char c : arrayName) {
        guard += static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
    }
    guard += "_H";
    return guard;
}

} // namespace

std::vector<std::uint8_t> encodeGeometry(const std::vector<Ring> &rings)
{
    std::vector<std::uint8_t> bytes;

    appendUint32LE(bytes, wrenium::geo::kInputGeometryMagic);
    appendUint32LE(bytes, wrenium::geo::kInputGeometryVersion);
    appendUint32LE(bytes, static_cast<std::uint32_t>(rings.size()));

    for (const Ring &ring : rings) {
        appendUint32LE(bytes, static_cast<std::uint32_t>(ring.size()));
        for (const wrenium::geo::GeoPoint &point : ring) {
            appendFloatLE(bytes, point.latRad);
            appendFloatLE(bytes, point.lonRad);
        }
    }

    return bytes;
}

void writeBinaryFile(const std::string &path, const std::vector<std::uint8_t> &bytes)
{
    std::ofstream file(path, std::ios::binary | std::ios::trunc);
    if (!file) {
        throw std::runtime_error("topojson2bin: failed to open output file: " + path);
    }

    file.write(reinterpret_cast<const char *>(bytes.data()), static_cast<std::streamsize>(bytes.size()));
    if (!file) {
        throw std::runtime_error("topojson2bin: failed to write output file: " + path);
    }
}

void writeHeaderFile(const std::string &path, const std::string &arrayName, const std::vector<std::uint8_t> &bytes)
{
    std::ofstream file(path, std::ios::trunc);
    if (!file) {
        throw std::runtime_error("topojson2bin: failed to open header file: " + path);
    }

    const std::string guard = toHeaderGuard(arrayName);

    file << "#ifndef " << guard << "\n";
    file << "#define " << guard << "\n\n";
    file << "// Generated by topojson2bin -- do not edit by hand.\n";
    file << "// Byte layout matches wrenium::geo::InputGeometryHeader, see\n";
    file << "// include/wrenium/geo/input_format.h.\n\n";
    file << "#include <cstddef>\n";
    file << "#include <cstdint>\n\n";
    file << "static const std::uint8_t " << arrayName << "[] = {\n";

    constexpr std::size_t kBytesPerLine = 12;
    for (std::size_t i = 0; i < bytes.size(); ++i) {
        if (i % kBytesPerLine == 0) {
            file << "    ";
        }

        file << "0x" << std::hex << std::setfill('0') << std::setw(2)
             << static_cast<unsigned>(bytes[i]);

        const bool isLast = (i + 1 == bytes.size());
        if (!isLast) {
            file << ",";
        }

        if ((i % kBytesPerLine == kBytesPerLine - 1) || isLast) {
            file << "\n";
        } else {
            file << " ";
        }
    }

    file << "};\n\n";
    file << "static const std::size_t " << arrayName << "Size = sizeof(" << arrayName << ");\n\n";
    file << "#endif // " << guard << "\n";

    if (!file) {
        throw std::runtime_error("topojson2bin: failed to write header file: " + path);
    }
}

} // namespace wrenium_geo_convert
